ltj/urls.py
from django.urls import include, path
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

from nature.api import router

urlpatterns = [
    path("auth/", include("social_django.urls", namespace="social")),
    path("helauth/", include("helusers.urls")),
    path("admin/", admin.site.urls),
    path("v1/", include(router.urls)),
    path("ltj/", include("nature.urls")),
]

admin.site.site_title = _("Luontotietojärjestelmä site admin")
admin.site.site_url = "/admin"

nature/urls.py
from django.conf.urls import url

from . import views

app_name = "nature"
urlpatterns = [
    url(
        r"^feature-report/(?P<pk>\d+)/$",
        views.FeatureReportView.as_view(),
        name="feature-report",
    ),
    url(
        r"^observationseries-report/(?P<pk>\d+)/$",
        views.ObservationSeriesReportView.as_view(),
        name="observationseries-report",
    ),
    url(
        r"^feature-observations-report/(?P<pk>\d+)/$",
        views.FeatureObservationsReportView.as_view(),
        name="feature-observations-report",
    ),
    url(
        r"^feature-habitattypeobservations-report/(?P<pk>\d+)/$",
        views.FeatureHabitatTypeObservationsReportView.as_view(),
        name="feature-habitattypeobservations-report",
    ),
    url(
        r"^species-report/(?P<pk>\d+)/$",
        views.SpeciesReportView.as_view(),
        name="species-report",
    ),
    url(
        r"^species-regulations-report/(?P<pk>\d+)/$",
        views.SpeciesRegulationsReportView.as_view(),
        name="species-regulations-report",
    ),
    url(
        r"^observation-report/(?P<pk>\d+)/$",
        views.ObservationReportView.as_view(),
        name="observation-report",
    ),
    url(r"^wfs", views.FeatureWFSView.as_view(), name="wfs"),
]

nature/views.py
import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView

from nature.hmac import HMACAuth
from .enums import UserRole
from .models import Feature, Species, ObservationSeries, Observation


class ProtectedReportViewMixin:
    """View mixin for protected reports

    Allow accessing all reports for staff users and public reports
    for non-staff users. If the requests is a hmac request, the
    reports are filtered based on forwarded authorization groups.
    """

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_staff:
            return qs

        hmac_auth = self._get_hmac_auth()
        role = hmac_auth.user_role
        if role == UserRole.ADMIN:
            return qs.for_admin()
        elif role == UserRole.OFFICE_HKI:
            return qs.for_office_hki()
        elif role == UserRole.OFFICE:
            return qs.for_office()

        return qs.www()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        admin_hmac_roles = [UserRole.ADMIN, UserRole.OFFICE_HKI, UserRole.OFFICE]
        hmac_auth = self._get_hmac_auth()
        user_role = (
            UserRole.ADMIN if self.request.user.is_staff else hmac_auth.user_role
        )
        user_is_in_admin_groups = (
            self.request.user.is_staff or hmac_auth.user_role in admin_hmac_roles
        )
        context_data["user_role"] = user_role.value
        context_data["user_is_in_admin_groups"] = user_is_in_admin_groups

        return context_data

    def _get_hmac_auth(self):
        if not hasattr(self, "_hmac_auth"):
            self._hmac_auth = HMACAuth(self.request)
        return self._hmac_auth


class ProtectedObservationListReportViewMixin(ProtectedReportViewMixin):
    """View mixin to filter observations based on user roles"""

    def get_observation_queryset(self):
        raise NotImplementedError

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data["observations"] = self.get_filtered_observations()
            context_data[
                "secret_observation_count"
            ] = self.get_secret_observation_count()
        return context_data

    def get_filtered_observations(self):
        """Get filtered observations based on hmac user roles"""
        qs = self.get_observation_queryset()
        if self.request.user.is_staff:
            return qs

        hmac_auth = self._get_hmac_auth()
        role = hmac_auth.user_role
        if role == UserRole.ADMIN:
            qs = qs.for_admin()
        elif role == UserRole.OFFICE_HKI:
            qs = qs.for_office_hki()
        elif role == UserRole.OFFICE:
            qs = qs.for_office()
        else:
            qs = qs.www()
        return qs

    def get_secret_observation_count(self):
        """Return the number of secret observations for current user role"""
        if self.request.user.is_staff:
            return 0

        hmac_auth = self._get_hmac_auth()
        user_role = hmac_auth.user_role

        if user_role not in [UserRole.OFFICE_HKI, user_role.OFFICE]:
            return 0

        qs = self.get_observation_queryset()
        admin_qs = qs.for_admin()
        office_qs = (
            qs.for_office_hki() if user_role == UserRole.OFFICE_HKI else qs.for_office()
        )

        return admin_qs.difference(office_qs).count()


class ValidRegulationsViewMixin(ProtectedReportViewMixin):
    def get_regulations_queryset(self):
        raise NotImplementedError

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data["regulations"] = self.get_filtered_regulations()
        return context_data

    def get_filtered_regulations(self):
        qs = self.get_regulations_queryset().exclude(valid=False)
        return qs


class FeatureReportView(
    ProtectedObservationListReportViewMixin, ProtectedReportViewMixin, DetailView
):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data[
                "transactions"
            ] = self.object.transactions.all().prefetch_related("regulations")
        return context_data


class ObservationReportView(ProtectedReportViewMixin, DetailView):
    queryset = Observation.objects.all()
    template_name = "nature/reports/observation-report.html"


class SpeciesReportView(
    ProtectedObservationListReportViewMixin, ValidRegulationsViewMixin, DetailView
):
    queryset = Species.objects.all()
    template_name = "nature/reports/species-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all().order_by("feature__feature_class__name")

    def get_regulations_queryset(self):
        return self.object.regulations.all()


class SpeciesRegulationsReportView(ValidRegulationsViewMixin, DetailView):
    model = Species
    template_name = "nature/reports/species-regulations-report.html"

    def get_regulations_queryset(self):
        return self.object.regulations.all()


class ObservationSeriesReportView(DetailView):
    queryset = ObservationSeries.objects.all()
    template_name = "nature/reports/observationseries-report.html"


class FeatureObservationsReportView(
    ProtectedObservationListReportViewMixin, DetailView
):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-observations-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all().order_by("species__name_fi")


class FeatureHabitatTypeObservationsReportView(ProtectedReportViewMixin, DetailView):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-habitattypeobservations-report.html"


@method_decorator(login_required, name="dispatch")
class FeatureWFSView(View):
    def get(self, request, *args, **kwargs):
        url = self._get_wfs_url()
        r = requests.get(url)
        return HttpResponse(
            content=r.content,
            content_type=r.headers["content-type"],
            status=r.status_code,
        )

    def _get_wfs_url(self):
        query_dict = self.request.GET.copy()
        query_dict.setlist("typeName", [self._get_layer_typename()])
        return "{0}?{1}".format(settings.WFS_SERVER_URL, query_dict.urlencode())

    def _get_layer_typename(self):
        return "{0}:{1}".format(
            settings.WFS_NAMESPACE, self.request.GET.get("typeName")
        )

nature/templates/nature/feature-report.html
{% load static i18n %}<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.5/ol.css" type="text/css" media="all" rel="stylesheet">
    <style>
        #map {
            height: 500px;
            width: 100%;
        }

        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }

        #background-map {
            margin-left: 15px;
        }
    </style>
</head>
<body>
<div class="container">
    <h2 class="text-uppercase">{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }})</h2>
    <hr class="mb-2">

    <!-- Area and geometry -->
    <div class="row">
        <b class="col-sm-2">{% trans "Area (from map)" %}</b>
        <div class="col-sm-10">
            {{ feature.area }} ha
        </div>
    </div>
    <div class="row mb-2">
        <label for="background-map" class="col-sm-2 col-form-label font-weight-bold">{% trans "Backgroud map" %}</label>
        <select id="background-map" class="col-sm-3 form-control" onchange="reportMap.changeLayer(this.value)">
            <option value="avoindata:Opaskartta_Helsinki">Opaskartta Helsinki</option>
            <option value="avoindata:Kantakartta">Kantakartta</option>
            <option value="avoindata:Kantakartan_maastotiedot">Kantakartan maastotiedot</option>
            <option value="avoindata:Kiinteistokartta">Kiinteistokartta</option>
            <option value="avoindata:Kiinteistokartan_maastotiedot">Kiinteistokartan maastotiedot</option>
            <option value="avoindata:Opaskartta_PKS">Opaskartta PKS</option>
            <option value="avoindata:Ortoilmakuva" selected>Ortoilmakuva</option>
        </select>
    </div>
    <div id="map"></div>
    <hr class="mb-2">

    <!-- Feature values -->
    {% if feature.values.all %}
        <h4 class="text-uppercase">{% trans "Feature values" %}</h4>
        <div class="row">
            {% for value in feature.values.all %}
                <div class="col-md-4">{{ value.value_type }}</div>
                <div class="col-md-4">{{ value.valuator }}</div>
                <div class="col-md-4"><a href="{{ value.link }}">{% trans "Value type basics" %}</a></div>
            {% endfor %}
        </div>
        <hr class="mb-2">
    {% endif %}

    <!-- Feature description -->
    {% if feature.text_display %}
        <h4 class="text-uppercase">{% trans "Feature description" %}</h4>
        <p>{{ feature.text_display|safe }}</p>
        <hr class="mb-2">
    {% endif %}

    {% if feature.transactions.all %}
        <h4 class="text-uppercase">{% trans "Feature transactions" %}</h4>
        {% for transaction in feature.transactions.all %}
            <div class="row mb-0">
                <b class="col-sm-2">{% trans "Date" %}</b>
                <div class="col-sm-10">
                    {{ transaction.date|date:'d.m.Y' }}
                </div>
            </div>
            <div class="form-group row mb-0">
                <b class="col-sm-2">{% trans "Transaction type" %}</b>
                <div class="col-sm-10">
                    {{ transaction.transaction_type }}
                </div>
            </div>
            <div class="form-group row mb-0">
                <b class="col-sm-2">{% trans "Description" %}</b>
                <div class="col-sm-10">
                    {{ transaction.description }}
                </div>
            </div>
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-2">
    {% endif %}
    {% if feature.observations.all %}
        {% if feature.geometry.geom_type == 'Point' %}
            <h4 class="text-uppercase">{% trans "Observations" %}</h4>
            {% for observation in feature.observations.all %}
                {% include "nature/stubs/observation-info.html" with observation=observation %}
                {% if not forloop.last %}
                    <hr class="mb-2 dashed">
                {% endif %}
            {% endfor %}
        {% else %}
            <a href="{% url 'nature:featureobservation-report' feature.id %}">
                {% trans "Observations at this feature" %}
            </a>
        {% endif %}
    {% endif %}

    {% if feature.habitat_type_observations.all %}
        {% if feature.habitat_type_observations.all|length == 1 %}
            <h4 class="text-uppercase">{% trans "Habitat type" %}</h4>
            {% include "nature/stubs/habitatobservation-info.html" with observation=feature.habitat_type_observations.first %}
        {% else %}
            <a href="{% url 'nature:featureobservation-report' feature.id %}">
                {% trans "Habitat observations at this feature" %}
            </a>
        {% endif %}

    {% endif %}
    <hr class="mb-2">
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.5/ol.js"></script>
<script src="{% static 'nature/js/ReportMap.js' %}"></script>
<script type="text/javascript">
    var reportMap = new ReportMap('map', '{{ feature.geometry.geojson|safe }}');
</script>
</body>
</html>

nature/templates/nature/featurehabitatobservation-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }})</h2>
    <hr class="mb-2">


    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{{ feature.name }}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if feature.habitat_type_observations.all %}
        <h4 class="text-uppercase">{% trans "Habitat types" %}</h4>
        <hr class="mb-2">

        {% for observation in feature.habitat_type_observations.all %}
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat type" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.name }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat group" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.group }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat code" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.code }}
                </div>
            </div>
            {% if observation.habitat_type.description %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat description" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.description }}
                    </div>
                </div>
            {% endif %}
            {% if observation.habitat_type.additional_info %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat additional info" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.additional_info | safe }}
                    </div>
                </div>
            {% endif %}
            {% if observation.observation_series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation series" %}</b>
                    <div class="col-sm-9">
                        <a href="{% url 'nature:observationseries-report' observation.observation_series.id %}">{{ observation.observation_series.name }}</a>
                    </div>
                </div>
            {% endif %}
            {% if observation.observation_series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Group fraction" %} %</b>
                    <div class="col-sm-9">
                        {{ observation.group_fraction }}
                    </div>
                </div>
            {% endif %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>

nature/templates/nature/featureobservation-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }})</h2>
    <hr class="mb-2">


    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{{ feature.name }}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if feature.observations.all %}
        <h4 class="text-uppercase">{% trans "Observations" %}</h4>
        <hr class="mb-2">

        {% for observation in feature.observations.all %}
            <div class="row">
                <b class="col-sm-3">{% trans "Species" %}</b>
                <div class="col-sm-9">
                    <a href="{% url 'nature:species-report' observation.species.id %}">
                        {{ observation.species.name_fi }} (<i>{{ observation.species.name_sci_1 }}</i>)
                    </a>
                </div>
            </div>
            {% if observation.species.additional_info %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Species information" %}</b>
                    <div class="col-sm-9">
                        {{ observation.species.additional_info }}
                    </div>
                </div>
            {% endif %}
            {% if observation.number %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Number" %}</b>
                    <div class="col-sm-9">
                        {{ observation.number }}
                    </div>
                </div>
            {% endif %}
            {% if observation.description %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation description" %}</b>
                    <div class="col-sm-9">
                        {{ observation.description }}
                    </div>
                </div>
            {% endif %}
            {% if observation.series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation series" %}</b>
                    <div class="col-sm-9">
                        <a href="{% url 'nature:observationseries-report' observation.series.id %}">{{ observation.series.name }}</a>
                    </div>
                </div>
            {% endif %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>

nature/templates/nature/observation-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{% trans "Observation" %}</h2>
    <hr class="mb-4">

    {% include "nature/stubs/observation-info.html" with observation=observation %}
    <hr class="mb-4">
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>

nature/templates/nature/openlayers-nature.html
{% load i18n l10n %}
<style type="text/css">{% block map_css %}{% get_current_language_bidi as LANGUAGE_BIDI %}
    #{{ id }}_map { width: {{ map_width }}px; height: {{ map_height }}px; }
    #{{ id }}_map .aligned label { float: inherit; }
    #{{ id }}_div_map { position: relative; vertical-align: top; float: {{ LANGUAGE_BIDI|yesno:"right,left" }}; }
    {% if not display_raw %}#{{ id }} { display: none; }{% endif %}
    .disable-edit, .is-editing .enable-edit { display: none; }
    .enable-edit, .is-editing .disable-edit { display: inline; }
    {% endblock %}
</style>

<div id="popup" class="ol-popup">
  <a href="javascript:{{ module }}.closeFeaturePopup()" id="popup-closer" class="ol-popup-closer"></a>
  <div id="popup-content"></div>
</div>

<div id="{{ id }}_div_map">
    <div id="{{ id }}_map"></div>
    {% if not disabled %}
    <span class="edit_features">
        <a href="javascript:{{ module }}.editFeatures()">
            <span class="enable-edit">{% trans "Edit" %}</span><span class="disable-edit">{% trans "Stop editing" %}</span>
        </a>
    </span> |
    <span class="clear_features"><a href="javascript:{{ module }}.clearFeatures()">{% trans "Delete all Geometries" %}</a></span>
    {% endif %}
    {% if display_raw %}<p>{% trans "Debugging window (serialized value)" %}</p>{% endif %}
    <textarea id="{{ id }}" class="vSerializedField required" cols="150" rows="10" name="{{ name }}">{{ serialized }}</textarea>
    <script type="text/javascript">
        {% block map_options %}var map_options = {};{% endblock %}
        {% block options %}var options = {
            geom_name: '{{ geom_type }}',
            id: '{{ id }}',
            map_id: '{{ id }}_map',
            map_options: map_options,
            map_srid: {{ map_srid|unlocalize }},
            name: '{{ name }}',
            default_x: {{ default_x|unlocalize }},
            default_y: {{ default_y|unlocalize }},
            default_zoom: {{ default_zoom|unlocalize }},
            wfs_server_url: '{% url 'nature:wfs' %}'
        };
        {% endblock %}
        var {{ module }} = new MapWidget(options);
    </script>
</div>

nature/templates/nature/species-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{% trans "Species report" %}</h2>
    <hr class="mb-2">


    <!-- Species -->
    <div class="row">
        <b class="col-sm-2">{% trans "Species" %}</b>
        <div class="col-sm-10">
            <i>{{ species.name_sci_1 | lower | capfirst }}</i>
            <br/>
            {{ species.name_fi | lower | capfirst }}
        </div>
    </div>
    <div class="row">
        <b class="col-sm-2">{% trans "Taxon" %}</b>
        <div class="col-sm-10">
            {{ species.taxon | lower | capfirst }}

            {% if species.taxon_1 %}
                <br/>
                {{ species.taxon_1 | lower | capfirst }}
            {% endif %}

            {% if species.taxon_2 %}
                <br/>
                {{ species.taxon_2 | lower | capfirst }}
            {% endif %}
        </div>
    </div>
    <hr class="mb-4">

    <!-- Regulations -->
    {% if species.regulations.all %}
        <h4 class="text-uppercase">
            {% trans "Regulations" %}
            <small>
                <a href="{% url 'nature:speciesregulation-report' species.id %}">
                    {% trans "Link" %}
                </a>
            </small>
        </h4>
        <hr class="mb-2">

        {% for regulation in species.regulations.all %}
            {% include 'nature/stubs/species-regulation.html' with regulation=regulation %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}

    <!-- Features -->
    {% if feature_classes %}
        <h4 class="text-uppercase">{% trans "Features" %}</h4>
        <hr class="mb-3">

        {% for feature_class_id, feature_class in feature_classes.items %}
            {% if not forloop.first %}
                <hr class="mb-3 strong">
            {% endif %}
            <h5 class="text-uppercase">{{ feature_class.name }}</h5>
            <hr class="mb-2 strong">
            {% for observation in feature_class.observations %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Name" %}</b>
                    <div class="col-sm-10">
                        {{ observation.feature.name }}
                    </div>
                </div>

                <div class="row">
                    <b class="col-sm-2">{% trans "Feature" %}</b>
                    <div class="col-sm-10">
                        <a href="{% url 'nature:feature-report' observation.feature.id %}">{{ observation.feature.id }}</a>
                    </div>
                </div>

                {% if observation.series.id %}
                    <div class="row">
                        <b class="col-sm-2">{% trans "Observation series" %}</b>
                        <div class="col-sm-10">
                            <a href="{% url 'nature:observationseries-report' observation.series.id %}">{{ observation.series.name }}</a>
                        </div>
                    </div>
                {% endif %}

                {% if observation.number %}
                    <div class="row">
                        <b class="col-sm-2">{% trans "Number" %}</b>
                        <div class="col-sm-10">
                            {{ observation.number }}
                        </div>
                    </div>
                {% endif %}

                {% if observation.description %}
                    <div class="row">
                        <b class="col-sm-2">{% trans "Description" %}</b>
                        <div class="col-sm-10">
                            {{ observation.description }}
                        </div>
                    </div>
                {% endif %}
                {% if not forloop.last %}
                    <hr class="mb-2 dashed">
                {% endif %}
            {% endfor %}
        {% endfor %}
        <hr class="mb-2">
    {% endif %}
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>