ltj/urls.py
from django.urls import include, path
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

from nature.api import router

urlpatterns = [
    path("auth/", include("social_django.urls", namespace="social")),
    path("helauth/", include("helusers.urls")),
    path("admin/", admin.site.urls),
    path("v1/", include(router.urls)),
    path("ltj/", include("nature.urls")),
]

admin.site.site_title = _("Luontotietojärjestelmä site admin")
admin.site.site_url = "/admin"

nature/urls.py
from django.conf.urls import url

from . import views

app_name = "nature"
urlpatterns = [
    url(
        r"^feature-report/(?P<pk>\d+)/$",
        views.FeatureReportView.as_view(),
        name="feature-report",
    ),
    url(
        r"^observationseries-report/(?P<pk>\d+)/$",
        views.ObservationSeriesReportView.as_view(),
        name="observationseries-report",
    ),
    url(
        r"^feature-observations-report/(?P<pk>\d+)/$",
        views.FeatureObservationsReportView.as_view(),
        name="feature-observations-report",
    ),
    url(
        r"^feature-habitattypeobservations-report/(?P<pk>\d+)/$",
        views.FeatureHabitatTypeObservationsReportView.as_view(),
        name="feature-habitattypeobservations-report",
    ),
    url(
        r"^species-report/(?P<pk>\d+)/$",
        views.SpeciesReportView.as_view(),
        name="species-report",
    ),
    url(
        r"^species-regulations-report/(?P<pk>\d+)/$",
        views.SpeciesRegulationsReportView.as_view(),
        name="species-regulations-report",
    ),
    url(
        r"^observation-report/(?P<pk>\d+)/$",
        views.ObservationReportView.as_view(),
        name="observation-report",
    ),
    url(r"^wfs", views.FeatureWFSView.as_view(), name="wfs"),
]

nature/views.py
import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView

from nature.hmac import HMACAuth
from .enums import UserRole
from .models import Feature, Species, ObservationSeries, Observation


class ProtectedReportViewMixin:
    """View mixin for protected reports

    Allow accessing all reports for staff users and public reports
    for non-staff users. If the requests is a hmac request, the
    reports are filtered based on forwarded authorization groups.
    """

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_staff:
            return qs

        hmac_auth = self._get_hmac_auth()
        role = hmac_auth.user_role
        if role == UserRole.ADMIN:
            return qs.for_admin()
        elif role == UserRole.OFFICE_HKI:
            return qs.for_office_hki()
        elif role == UserRole.OFFICE:
            return qs.for_office()

        return qs.www()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        admin_hmac_roles = [UserRole.ADMIN, UserRole.OFFICE_HKI, UserRole.OFFICE]
        hmac_auth = self._get_hmac_auth()
        user_role = (
            UserRole.ADMIN if self.request.user.is_staff else hmac_auth.user_role
        )
        user_is_in_admin_groups = (
            self.request.user.is_staff or hmac_auth.user_role in admin_hmac_roles
        )
        context_data["user_role"] = user_role.value
        context_data["user_is_in_admin_groups"] = user_is_in_admin_groups

        return context_data

    def _get_hmac_auth(self):
        if not hasattr(self, "_hmac_auth"):
            self._hmac_auth = HMACAuth(self.request)
        return self._hmac_auth


class ProtectedObservationListReportViewMixin(ProtectedReportViewMixin):
    """View mixin to filter observations based on user roles"""

    def get_observation_queryset(self):
        raise NotImplementedError

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data["observations"] = self.get_filtered_observations()
            context_data[
                "secret_observation_count"
            ] = self.get_secret_observation_count()
        return context_data

    def get_filtered_observations(self):
        """Get filtered observations based on hmac user roles"""
        qs = self.get_observation_queryset()
        if self.request.user.is_staff:
            return qs

        hmac_auth = self._get_hmac_auth()
        role = hmac_auth.user_role
        if role == UserRole.ADMIN:
            qs = qs.for_admin()
        elif role == UserRole.OFFICE_HKI:
            qs = qs.for_office_hki()
        elif role == UserRole.OFFICE:
            qs = qs.for_office()
        else:
            qs = qs.www()
        return qs

    def get_secret_observation_count(self):
        """Return the number of secret observations for current user role"""
        if self.request.user.is_staff:
            return 0

        hmac_auth = self._get_hmac_auth()
        user_role = hmac_auth.user_role

        if user_role not in [UserRole.OFFICE_HKI, user_role.OFFICE]:
            return 0

        qs = self.get_observation_queryset()
        admin_qs = qs.for_admin()
        office_qs = (
            qs.for_office_hki() if user_role == UserRole.OFFICE_HKI else qs.for_office()
        )

        return admin_qs.difference(office_qs).count()


class ValidRegulationsViewMixin(ProtectedReportViewMixin):
    def get_regulations_queryset(self):
        raise NotImplementedError

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data["regulations"] = self.get_filtered_regulations()
        return context_data

    def get_filtered_regulations(self):
        qs = self.get_regulations_queryset().exclude(valid=False)
        return qs


class FeatureReportView(
    ProtectedObservationListReportViewMixin, ProtectedReportViewMixin, DetailView
):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.object:
            context_data[
                "transactions"
            ] = self.object.transactions.all().prefetch_related("regulations")
        return context_data


class ObservationReportView(ProtectedReportViewMixin, DetailView):
    queryset = Observation.objects.all()
    template_name = "nature/reports/observation-report.html"


class SpeciesReportView(
    ProtectedObservationListReportViewMixin, ValidRegulationsViewMixin, DetailView
):
    queryset = Species.objects.all()
    template_name = "nature/reports/species-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all().order_by("feature__feature_class__name")

    def get_regulations_queryset(self):
        return self.object.regulations.all()


class SpeciesRegulationsReportView(ValidRegulationsViewMixin, DetailView):
    model = Species
    template_name = "nature/reports/species-regulations-report.html"

    def get_regulations_queryset(self):
        return self.object.regulations.all()


class ObservationSeriesReportView(DetailView):
    queryset = ObservationSeries.objects.all()
    template_name = "nature/reports/observationseries-report.html"


class FeatureObservationsReportView(
    ProtectedObservationListReportViewMixin, DetailView
):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-observations-report.html"

    def get_observation_queryset(self):
        return self.object.observations.all().order_by("species__name_fi")


class FeatureHabitatTypeObservationsReportView(ProtectedReportViewMixin, DetailView):
    queryset = Feature.objects.all()
    template_name = "nature/reports/feature-habitattypeobservations-report.html"


@method_decorator(login_required, name="dispatch")
class FeatureWFSView(View):
    def get(self, request, *args, **kwargs):
        url = self._get_wfs_url()
        r = requests.get(url)
        return HttpResponse(
            content=r.content,
            content_type=r.headers["content-type"],
            status=r.status_code,
        )

    def _get_wfs_url(self):
        query_dict = self.request.GET.copy()
        query_dict.setlist("typeName", [self._get_layer_typename()])
        return "{0}?{1}".format(settings.WFS_SERVER_URL, query_dict.urlencode())

    def _get_layer_typename(self):
        return "{0}:{1}".format(
            settings.WFS_NAMESPACE, self.request.GET.get("typeName")
        )

nature/templates/nature/reports/feature-habitatobservation-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }})</h2>
    <hr class="mb-2">


    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{{ feature.name }}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if feature.habitat_type_observations.all %}
        <h4 class="text-uppercase">{% trans "Habitat types" %}</h4>
        <hr class="mb-2">

        {% for observation in feature.habitat_type_observations.all %}
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat type" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.name }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat group" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.group }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat code" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.code }}
                </div>
            </div>
            {% if observation.habitat_type.description %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat description" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.description }}
                    </div>
                </div>
            {% endif %}
            {% if observation.habitat_type.additional_info %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat additional info" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.additional_info | safe }}
                    </div>
                </div>
            {% endif %}
            {% if observation.observation_series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation series" %}</b>
                    <div class="col-sm-9">
                        <a href="{% url 'nature:observationseries-report' observation.observation_series.id %}">{{ observation.observation_series.name }}</a>
                    </div>
                </div>
            {% endif %}
            {% if observation.observation_series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Group fraction" %} %</b>
                    <div class="col-sm-9">
                        {{ observation.group_fraction }}
                    </div>
                </div>
            {% endif %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>

nature/templates/nature/reports/feature-habitattypeobservations-report.html
{% extends 'nature/reports/report-base.html' %}
{% load i18n %}

{% block title %}{% trans "Feature Report - Habitat Type Observations" %} - {{ user_role }}{% endblock %}

{% block extrastyles %}
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
{% endblock %}

{% block report_header %}{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }}){% endblock %}

{% block report_body %}
    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{{ feature.name }}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if feature.habitat_type_observations.all %}
        <h4 class="text-uppercase">{% trans "Habitat types" %}</h4>
        <hr class="mb-2">

        {% for observation in feature.habitat_type_observations.all %}
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat type" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.name }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat group" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.group }}
                </div>
            </div>
            <div class="row">
                <b class="col-sm-3">{% trans "Habitat code" %}</b>
                <div class="col-sm-9">
                    {{ observation.habitat_type.code }}
                </div>
            </div>
            {% if observation.habitat_type.description %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat description" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.description }}
                    </div>
                </div>
            {% endif %}
            {% if observation.habitat_type.additional_info %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Habitat additional info" %}</b>
                    <div class="col-sm-9">
                        {{ observation.habitat_type.additional_info | safe }}
                    </div>
                </div>
            {% endif %}
            {% if observation.observation_series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation series" %}</b>
                    <div class="col-sm-9">
                        <a href="{% url 'nature:observationseries-report' observation.observation_series.id %}">{{ observation.observation_series.name }}</a>
                    </div>
                </div>
            {% endif %}
            {% if observation.group_fraction %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Group fraction" %} %</b>
                    <div class="col-sm-9">
                        {{ observation.group_fraction }}
                    </div>
                </div>
            {% endif %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

nature/templates/nature/reports/feature-observation-report.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
</head>
<body>

<div class="container">
    <div id="image-container"></div>
    <h2 class="text-uppercase">{{ feature.feature_class.name }} <br> {{ feature.name }} ({{ feature.fid }})</h2>
    <hr class="mb-2">


    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{{ feature.name }}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if feature.observations.all %}
        <h4 class="text-uppercase">{% trans "Observations" %}</h4>
        <hr class="mb-2">

        {% for observation in feature.observations.all %}
            <div class="row">
                <b class="col-sm-3">{% trans "Species" %}</b>
                <div class="col-sm-9">
                    <a href="{% url 'nature:species-report' observation.species.id %}">
                        {{ observation.species.name_fi }} (<i>{{ observation.species.name_sci_1 }}</i>)
                    </a>
                </div>
            </div>
            {% if observation.species.additional_info %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Species information" %}</b>
                    <div class="col-sm-9">
                        {{ observation.species.additional_info }}
                    </div>
                </div>
            {% endif %}
            {% if observation.number %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Number" %}</b>
                    <div class="col-sm-9">
                        {{ observation.number }}
                    </div>
                </div>
            {% endif %}
            {% if observation.description %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation description" %}</b>
                    <div class="col-sm-9">
                        {{ observation.description }}
                    </div>
                </div>
            {% endif %}
            {% if observation.series.id %}
                <div class="row">
                    <b class="col-sm-3">{% trans "Observation series" %}</b>
                    <div class="col-sm-9">
                        <a href="{% url 'nature:observationseries-report' observation.series.id %}">{{ observation.series.name }}</a>
                    </div>
                </div>
            {% endif %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}
    <footer>
        <p class="mb-1">© Helsingin kaupunki</p>
        <p>Luontotietojärjestelmä</p>
    </footer>
</div>
</body>
</html>

nature/templates/nature/reports/feature-observations-report.html
{% extends 'nature/reports/report-base.html' %}
{% load i18n %}

{% block title %}{% trans "Feature Report - Observations" %} - {{ user_role }}{% endblock %}

{% block extrastyles %}
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
{% endblock %}

{% block report_header %}{{ feature.feature_class.name }}<br>{% if feature.name %}{{ feature.name }}{% endif %}{% if feature.fid %}({{ feature.fid }}){% endif %}{% endblock %}

{% block report_body %}
    <!-- Feature -->
    <div class="row">
        <b class="col-sm-2">{% trans "Feature" %}</b>
        <div class="col-sm-10">
            <a href="{% url 'nature:feature-report' feature.id %}">{% if feature.name %}{{ feature.name }}{% elif feature.fid %}{{ feature.fid }}{% else %}{% trans "Link" %}{% endif %}</a>
        </div>
    </div>

    <hr class="mb-4">
    {% if observations %}
        <h4 class="text-uppercase">{% trans "Observations" %}</h4>
        <hr class="mb-2">

        {% for observation in observations %}
            {% include "nature/reports/stubs/observation-info.html" with observation=observation %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if secret_observation_count %}
        <hr class="mb-2 dashed">
        <div class="row">
            <b class="col-sm-3 text-uppercase">
                {% blocktrans count counter=secret_observation_count %}{{ counter }} secret observation{% plural %}{{ counter }} secret observations{% endblocktrans %}
            </b>
        </div>
    {% endif %}
{% endblock %}

nature/templates/nature/reports/observation-report.html
{% extends "nature/reports/report-base.html" %}
{% load i18n %}

{% block title %}{% trans "Observation Report" %} - {{ user_role }}{% endblock %}

{% block report_header %}{% trans "Observation" %}{% endblock %}

{% block report_body %}
    {% include "nature/reports/stubs/observation-info.html" with observation=observation %}
{% endblock %}

nature/templates/nature/reports/observationseries-report.html
{% extends "nature/reports/report-base.html" %}
{% load i18n %}

{% block title %}{% trans "Observation Series Report" %} - {{ user_role }}{% endblock %}

{% block extrastyles %}
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
{% endblock %}

{% block report_header %}{{ observationseries.name }}{% endblock %}

{% block report_body %}
    <div class="row">
        <b class="col-sm-3">{% trans "Name" %}</b>
        <div class="col-sm-9">
            {{ observationseries.name }}
        </div>
    </div>
    {% if observationseries.description %}
        <div class="row">
            <b class="col-sm-3">{% trans "Description" %}</b>
            <div class="col-sm-9">
                {{ observationseries.description }}
            </div>
        </div>
    {% endif %}
    {% if observationseries.start_date %}
        <div class="row">
            <b class="col-sm-3">{% trans "Start date" %}</b>
            <div class="col-sm-9">
                {{ observationseries.start_date|date:'d.m.Y' }}
            </div>
        </div>
    {% endif %}
    {% if observationseries.end_date %}
        <div class="row">
            <b class="col-sm-3">{% trans "End date" %}</b>
            <div class="col-sm-9">
                {{ observationseries.end_date|date:'d.m.Y' }}
            </div>
        </div>
    {% endif %}
{% endblock %}

nature/templates/nature/reports/species-report.html
{% extends "nature/reports/report-base.html" %}
{% load i18n %}

{% block title %}{% trans "Species Report" %} - {{ user_role }}{% endblock %}

{% block extrastyles %}
    <style>
        hr.dashed {
            border: none;
            border-top: 1px dashed rgba(0, 0, 0, .1);
        }

        hr.strong {
            border: none;
            border-top: 2px solid rgba(0, 0, 0, .1);
        }

        .row {
            margin-bottom: .3rem;
        }
    </style>
{% endblock %}

{% block report_header %}{% trans "Species report" %}{% endblock %}

{% block report_body %}
    <!-- Species -->
    <div class="row">
        <b class="col-sm-2">{% trans "Species" %}</b>
        <div class="col-sm-10">
            {{ species.name_fi | lower | capfirst }}
            <br/>
            <i>
                {% if species.name_sci_1 %}{{ species.name_sci_1 | lower | capfirst }}{% endif %} 
                {% if species.name_subspecies_1 %}{{ species.name_subspecies_1 | lower }}{% endif %}
            </i>
        </div>
    </div>
    <div class="row">
        <b class="col-sm-2">{% trans "Taxon" %}</b>
        <div class="col-sm-10">
            {{ species.taxon | lower | capfirst }}

            {% if species.taxon_1 %}
                <br/>
                {{ species.taxon_1 | lower | capfirst }}
            {% endif %}
        </div>
    </div>
    {% if species.link %}
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <a target="_blank" rel="noopener noreferrer" href="{{ species.link }}">{% trans "Link" %}a>
            </div>
        </div>
    {% endif %}
    <hr class="mb-4">

    <!-- Regulations -->
    {% if regulations %}
        <h4 class="text-uppercase">
            {% trans "Regulations" %}
            <small>
                <a href="{% url 'nature:species-regulations-report' species.id %}">
                    {% trans "Link" %}
                </a>
            </small>
        </h4>
        <hr class="mb-2">

        {% for regulation in regulations %}
            {% include 'nature/reports/stubs/species-regulation.html' with regulation=regulation %}
            {% if not forloop.last %}
                <hr class="mb-2 dashed">
            {% endif %}
        {% endfor %}
        <hr class="mb-4">
    {% endif %}

    <!-- Features observations -->
    {% if observations %}
        <h4 class="text-uppercase">{% trans "Features" %}</h4>
        {% for observation in observations %}
            {% with observation.feature.feature_class as feature_class %}
                {% ifchanged feature_class %}
                    {% if not forloop.first %}
                        <hr class="mb-3 strong">  {# seperator between feature classes #}
                    {% endif %}
                    <div class="row">
                        <div class="col-sm-2 font-weight-bold text-uppercase">{% trans "feature class" %}</div>
                        <div class="col-sm-10 text-uppercase">{{ feature_class }}</div>
                    </div>
                    <hr class="mb-2 strong">
                {% else %}
                    <hr class="mb-2 dashed">
                {% endifchanged %}
            {% endwith %}

            {% if observation.feature.name %}
            <div class="row">
                <b class="col-sm-2">{% trans "Name" %}</b>
                <div class="col-sm-10">
                    {{ observation.feature.name }}
                </div>
            </div>
            {% endif %}

            <div class="row">
                <b class="col-sm-2">{% trans "Feature" %}</b>
                <div class="col-sm-10">
                    <a href="{% url 'nature:feature-report' observation.feature.id %}">{% if observation.feature.fid %}{{ observation.feature.fid }}{% else %}{{ observation.feature.id }}{% endif %}</a>
                </div>
            </div>

            {% if observation.series.id %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Observation series" %}</b>
                    <div class="col-sm-10">
                        <a href="{% url 'nature:observationseries-report' observation.series.id %}">{{ observation.series.name }}</a>
                    </div>
                </div>
            {% endif %}

            {% if observation.abundance and not observation.abundance.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Abundance" %}</b>
                    <div class="col-sm-10">{{ observation.abundance }}</div>
                </div>
            {% endif %}

            {% if observation.frequency and not observation.frequency.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Frequence" %}</b>
                    <div class="col-sm-10">{{ observation.frequency }}</div>
                </div>
            {% endif %}

            {% if observation.number %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Number" %}</b>
                    <div class="col-sm-10">{{ observation.number }}</div>
                </div>
            {% endif %}

            {% if observation.migration_class and not observation.migration_class.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Migration class" %}</b>
                    <div class="col-sm-10">{{ observation.migration_class }}</div>
                </div>
            {% endif %}

            {% if observation.origin and not observation.origin.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Origin" %}</b>
                    <div class="col-sm-10">{{ observation.origin}}</div>
                </div>
            {% endif %}

            {% if observation.breeding_degree and not observation.breeding_degree.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Breeding degree" %}</b>
                    <div class="col-sm-10">{{ observation.breeding_degree}}</div>
                </div>
            {% endif %}

            {% if observation.description %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Description" %}</b>
                    <div class="col-sm-10">{{ observation.description}}</div>
                </div>
            {% endif %}

            {% if observation.notes %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Notes" %}</b>
                    <div class="col-sm-10">{{ observation.notes}}</div>
                </div>
            {% endif %}

            {% if observation.date %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Date" %}</b>
                    <div class="col-sm-10">{{ observation.date}}</div>
                </div>
            {% endif %}

            {% if observation.occurrence and not observation.occurrence.is_empty %}
                <div class="row">
                    <b class="col-sm-2">{% trans "Occurrence" %}</b>
                    <div class="col-sm-10">{{ observation.occurrence}}</div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if secret_observation_count %}
        <hr class="mb-2 dashed">
        <div class="row">
            <b class="col-sm-3 text-uppercase">
                {% blocktrans count counter=secret_observation_count %}{{ counter }} secret observation{% plural %}{{ counter }} secret observations{% endblocktrans %}
            </b>
        </div>
    {% endif %}
{% endblock %}